{% set name = "livox-sdk2" %}
{% set version = "1.2.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Livox-SDK/Livox-SDK2/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 38d65c969788285f298227fbd954eb253e2816e4a6a93a9bfc624cf91fb5e75a
    patches:
      - 0001-update-cmake-minimum-version.patch 
      - 0002-Add-missing-includes-for-ubuntu-24.04-comp.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja

test:
  commands:
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/Livox-SDK/Livox-SDK2
  license: MIT
  license_file: LICENSE.txt
  summary: Drivers for receiving LiDAR data and controlling lidar, support Lidar HAP and Mid-360.

extra:
  feedstock-name: livox-sdk2
  recipe-maintainers:
    - wep21
